### PR TITLE
Fixed improper behavior when on b-leg device is enabled DND feature

### PR DESCRIPTION
**Pull request by sergey-safarov**
Fixed improper behavior when on b-leg device is enabled DND feature
[DND-480.pcap.gz](https://github.com/2600hz/kazoo-configs-kamailio/files/1832453/DND-480.pcap.gz)

### CODE REVIEW

**Comment by k-anderson** [comment]
Howdy, I will have to take a look further when I have more time but at first glance if the b-leg rejects the INVITE from FreeSWITCH it should not end up in 'INTERNAL_FAULT'.  IE: FreeSWITCH to the device should be going through:
https://github.com/2600hz/kazoo-configs-kamailio/blob/master/kamailio/default.cfg#L643
which does not call t_on_failure. 

Admittedly I have not looked at the pcap yet so might make more sense after that ;)  I amworking another issue and saw this PR.

**Comment by sergey-safarov** [comment]
In cuurent case 480 code from b-leg is propagated via FS to Kamailio. Then Kamailio try recover this instread pass to a-leg.

**Comment by sergey-safarov** [comment]
@k-anderson, you are looking b-leg. Is required to look a-leg.

**Comment by lazedo** [comment]
@sergey-safarov i don't think this is still relevant, is it ? devices in `dnd` normally reply `486`

**Comment by sergey-safarov** [comment]
Hello Luis
Here example from Yealink phone with DND enabled feature.
[DND_from_yalink.pcap.gz](https://github.com/2600hz/kazoo-configs-kamailio/files/3902769/DND_from_yalink.pcap.gz)

Please check yealink setting param `features.dnd_refuse_code`. Default value `480`.

> Configures a return code and reason of SIP response messages when rejecting an
incoming call by DND. A specific reason is displayed on the caller’s phone LCD
screen.
404-No Found
480-Temporarily Unavailable
486-Busy Here
If it is set to 486 (Busy Here), the caller’s LCD screen will display the reason “Busy
Here” when the callee enables DND.

You can find at page 167 of [`Yealink_SIP-T4X_IP_Phones_Administrator_Guide_V73_40.pdf`](http://support.yealink.com/attachmentDownload/download?path=upload%2Fattachment%2F2015-3-10%2F3%2F0b6c94fb-606a-443e-a92e-5f947961dbc0%2FYealink_SIP-T4X_IP_Phones_Administrator_Guide_V73_40.pdf) and similar.

**Comment by lazedo** [comment]
@sergey-safarov closing this as not reproducible

**Pull request closed without merging**
