### PR TITLE
$fu with ' will crash kamailio with ACL role enabled

### PR DESCRIPTION
**Pull request by noahmehl**

### CODE REVIEW

**Comment by noahmehl** [comment]
@lazedo can you please take a look?

**Comment by lazedo** [comment]
@noahmehl if its because of acl role then fix whatever you're getting in acl role.

**Comment by noahmehl** [comment]
@lazedo it just happened to crash because of acl role, but almost everything is converted to json for the amqp messaging, so an unescaped apostrophe is not good in general...?

**Comment by lazedo** [comment]
@noahmehl `sanity_check()` above will complain about it. the problem is in acl role

**Comment by alanrevans** [comment]
@lazedo unfortunely sanity_check() doesn't catch this problem (at least not in kazoo-configs-kamailio-4.3.1).
Here is the log:
`
Nov 25 05:48:30 d1k1 kamailio[13564]: INFO: <script>: LoYESoIC3VKbVYsu.Call|log|original R-URI (sip:48525260159@54.39.12.200:5065) is this proxy, treating as external sources
Nov 25 05:48:30 d1k1 kamailio[13564]: WARNING: <script>: LoYESoIC3VKbVYsu.Call|ACL-realm|Fix for INVITE with IP in from URI: use to-domain
Nov 25 05:48:30 d1k1 kamailio[13564]: WARNING: <script>: LoYESoIC3VKbVYsu.Call|ACL-device|Fix for INVITE with IP in from URI: use to-domain
Nov 25 05:48:30 d1k1 kamailio[13654]: CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 151
Nov 25 05:48:30 d1k1 kamailio[13387]: ALERT: <core> [main.c:739]: handle_sigs(): child process 13564 exited by a signal 11
Nov 25 05:48:30 d1k1 kamailio[13387]: ALERT: <core> [main.c:742]: handle_sigs(): core was not generated
Nov 25 05:48:30 d1k1 kamailio[13387]: INFO: <core> [main.c:764]: handle_sigs(): terminating due to SIGCHLD
Nov 25 05:48:30 d1k1 kamailio[13466]: INFO: <core> [main.c:819]: sig_usr(): signal 15 received
Nov 25 05:48:30 d1k1 kamailio[13466]: INFO: <core> [main.c:835]: sig_usr(): Memory still-in-use summary (pkg):
`

And here is the backtrace:

`
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffec05955b in lh_table_lookup_entry (t=0xde87e0, k=k@entry=0x7fffec2d0092) at linkhash.c:529
#2  0x00007fffec05607c in json_object_object_add (jso=0xde8740, key=0x7fffec2d0092 "App-Name", val=0xde8790) at json_object.c:381
#3  0x00007fffec283d11 in kz_amqp_add_payload_common_properties (json_obj=0xde8740, server_id=0x7fffffffb5b0 "kamailio@build.sip.local-<19270>-script-0", unique=0x7fffffffb7b0) at kz_amqp.c:1020
#4  0x00007fffec28566b in kz_amqp_pipe_send_receive (str_exchange=0x7fffffffb8e0, str_routing_key=0x7fffffffb8d0, str_payload=0x7fffffffb8f0, kz_timeout=0x7fffffffb8c0, json_ret=0x7fffffffb8b8) at kz_amqp.c:1156
#5  0x00007fffec28c167 in kz_amqp_query_ex (msg=0x7ffff7276a30, exchange=0x7ffff71bfb68 "\360\372\033\367\377\177", routing_key=0x7ffff71bfc08 "\b\210\034\367\377\177", payload=0x7ffff6ef6148 "H\257(\367\377\177") at kz_amqp.c:1479
#6  0x00007fffec28c26d in kz_amqp_query (msg=0x7ffff7276a30, exchange=0x7ffff71bfb68 "\360\372\033\367\377\177", routing_key=0x7ffff71bfc08 "\b\210\034\367\377\177", payload=0x7ffff6ef6148 "H\257(\367\377\177",
    dst=0x7ffff71bfd28 "\017") at kz_amqp.c:1502
#7  0x000000000045c683 in do_action (h=0x7fffffffc120, a=0x7ffff71c8b90, msg=0x7ffff7276a30) at core/action.c:1142
#8  0x0000000000463d5c in run_actions (h=0x7fffffffc120, a=0x7ffff71c8b90, msg=0x7ffff7276a30) at core/action.c:1565
#9  0x0000000000464439 in run_actions_safe (h=0x7fffffffd9e0, a=0x7ffff71c8b90, msg=0x7ffff7276a30) at core/action.c:1633
#10 0x0000000000430005 in rval_get_int (h=0x7fffffffd9e0, msg=0x7ffff7276a30, i=0x7fffffffc8e0, rv=0x7ffff71cb080, cache=0x0) at core/rvalue.c:912
#11 0x000000000043459c in rval_expr_eval_int (h=0x7fffffffd9e0, msg=0x7ffff7276a30, res=0x7fffffffc8e0, rve=0x7ffff71cb078) at core/rvalue.c:1910
#12 0x0000000000457084 in do_action (h=0x7fffffffd9e0, a=0x7ffff71d5cd0, msg=0x7ffff7276a30) at core/action.c:1043
#13 0x0000000000463d5c in run_actions (h=0x7fffffffd9e0, a=0x7ffff71c7e98, msg=0x7ffff7276a30) at core/action.c:1565
#14 0x0000000000457518 in do_action (h=0x7fffffffd9e0, a=0x7ffff71d68a8, msg=0x7ffff7276a30) at core/action.c:1058
#15 0x0000000000463d5c in run_actions (h=0x7fffffffd9e0, a=0x7ffff719df58, msg=0x7ffff7276a30) at core/action.c:1565
#16 0x0000000000454004 in do_action (h=0x7fffffffd9e0, a=0x7ffff72a4fb0, msg=0x7ffff7276a30) at core/action.c:691
#17 0x0000000000463d5c in run_actions (h=0x7fffffffd9e0, a=0x7ffff72a2a00, msg=0x7ffff7276a30) at core/action.c:1565
#18 0x0000000000464501 in run_top_route (a=0x7ffff72a2a00, msg=0x7ffff7276a30, c=0x0) at core/action.c:1654
#19 0x000000000059bb41 in receive_msg (
    buf=0xa59240 <buf.6825> "INVITE sip:48525260159@192.95.15.8:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 10.0.0.20:5061;branch=z9hG4bK-19318-1-0\r\nFrom: <sip:admin'/*@172.83.45.42>;tag=1\r\nTo: sut <sip:48525260159@192.95.15.8>\r\nCall-ID: 1-19"..., len=501, rcv_info=0x7fffffffe000) at core/receive.c:286
#20 0x000000000049de99 in udp_rcv_loop () at core/udp_server.c:554
#21 0x0000000000422e52 in main_loop () at main.c:1439
#22 0x000000000042bb03 in main (argc=5, argv=0x7fffffffe548) at main.c:2677
`

And here is the string that kz_amqp is using to create a json object
`
"{'Event-Category': 'acl', 'Event-Name': 'query', 'Entity': 'admin'/*@192.95.15.8', 'With-Realm': true}"
`
Notice the ' in the Entity attribute.

**Comment by lazedo** [comment]
@alanrevans `sanity_check` will complain if its an invalid `uri` which is not. again, the problem is in `acl` role.

**Comment by alanrevans** [comment]
Just FYI this crash is fixed in 4.3.8 version of kazoo-configs-kamailio
'''
FYI: This crash is fixed in the latest kazoo-configs-kamailio (4.3.8) The AMQP query still fails but least it doesn't crash
Nov 27 14:43:08 build kamailio: WARNING: <script>: 1-5339@10.0.0.20|ACL-realm|Fix for INVITE with IP in from URI: use to-domain
Nov 27 14:43:08 build kamailio: WARNING: <script>: 1-5339@10.0.0.20|ACL-device|Fix for INVITE with IP in from URI: use to-domain
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|ACL log|Query: {'Event-Category': 'acl', 'Event-Name': 'query', 'Entity': 'admin/'*@192.95.15.8', 'With-Realm': true}
Nov 27 14:43:08 build kamailio: ERROR: kazoo [kz_amqp_pipe.c:234]: kz_amqp_query_ex_k(): empty or invalid JSON payload :
Nov 27 14:43:08 build kamailio: ERROR: <script>: 1-5339@10.0.0.20|ACL log|DB is unreachable
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|ACL|INVITE from 10.0.0.20 is permitted by ACL for admin/'*@192.95.15.8
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|start|received udp request INVITE sip:48525260159@192.95.15.8:5060
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|log|source 10.0.0.20:5061 -> 10.0.0.20:5060
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|log|from sip:admin/'*@172.83.45.42
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|log|to sip:48525260159@192.95.15.8
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|log|originated from external sources
Nov 27 14:43:08 build kamailio: INFO: <script>: 1-5339@10.0.0.20|pass|10.0.0.20:5060 -> 10.0.0.20:11000
'''

**Comment by lazedo** [comment]
@alanrevans its not about kazoo-configs-kamailio, its kamailio (kazoo module) which got updated by kazoo-kamailio meta package which references a new kamailio version where the payload is properly checked. again, the problem is in acl role

**Pull request closed without merging**
