### PR TITLE
Added ability to route call to device defined as SIP URI

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by k-anderson** [comment]
@sergey-safarov howdy, what is the condition when you would have both an AOR and a format of 'route'?  I would have expected if the format was route there would be no AOR present.

**Comment by sergey-safarov** [comment]
I have SIP device that cannot be register on kazoo but is reachable sip SIP uri.
I configured this device on kazoo as SIP-uri device and then make call.

**Comment by lazedo** [comment]
@sergey-safarov this looks like a hack to get extension calling for external pbx. is there a reason why you would not use trunstore in this case ?

**Comment by sergey-safarov** [comment]
Remote PBX have internal numbering plan 1100-1199 and number 1120 cannot be dialed as it recognised as emergency numbers 112.
I created SIP uri device and make call to callflow 2120 and than dial SIP uri device.
I have one such device and configure number translation on trunkstore link is overkill.
More simple use SIP uri.

What is purpose of SIP uri device  if kamailio cannot route call by SIP uri?

**Comment by lazedo** [comment]
@sergey-safarov you will only have this if fs_path is set in the route so it reaches kamailio, we don't want to support that use case for now.

**Pull request closed without merging**
