### PR TITLE
Addeded creation of active_watchers_log table for PostgreSQL.

### PR DESCRIPTION
**Pull request by sergey-safarov**
Adjusted location_attrs table to store long avalue.

### CODE REVIEW

**Comment by lazedo** [comment]
@sergey-safarov awesome, thanks. 
can you also add engine specific functions for `db_pre_setup`  and `resulted_sql_header` ? 
`db_pre_setup`  would be used to set some `pragma` instructions specific to the engine
`resulted_sql_header` would be used to fix any db engine related issue (like the one you proposing)
```
db_pre_setup > $RESULTED_SQL
resulted_sql_header >> $RESULTED_SQL
for i in $(get_sql_filelist); do
    cat $KAMAILIO_SHARE_DIR/$DB_ENGINE/$i >> $RESULTED_SQL
done
add_extra_tables >> $RESULTED_SQL
resulted_sql_footer >> $RESULTED_SQL
```

**Comment by sergey-safarov** [comment]
Hello @lazedo
Sorry for delay. I made script update.
All function now engine specific and separated to dedicated files.

**Comment by lazedo** [comment]
@sergey-safarov thanks. going to make some changes after this merge

**Comment by lazedo** [comment]
@sergey-safarov  post-merge follow up pr, https://github.com/2600hz/kazoo-configs-kamailio/pull/53

**Comment by sergey-safarov** [comment]
Hello @lazedo 
Small [fix](https://github.com/2600hz/kazoo-configs-kamailio/pull/55)

**Pull request merged**
